
const addFiles = {
    file: "",
    model: {
      entity: "Universidad Distrital Francisco José de Caldas",
    },
    title: "Crear recursos",
    result: { state: false },
    schema: {
      fields: [
        {
          type: "label",
          label: "<h3>General</h3>",
          model: "created",
          styleClasses: "blue lighten-4 text-md-center",
        },
        {
          type: "input",
          inputType: "text",
          label: "Título",
          model: "title",
          placeholder: "Título del recurso",
          featured: true,
          required: true,
        },
        {
          type: "select",
          inputType: "text",
          label: "Idioma",
          model: "language",
          placeholder: "Idioma del recurso",
          featured: true,
          required: true,
          values: ["Español", "Inlgés"],
          default: "Español",
        },
        {
          type: "input",
          inputType: "text",
          label: "Descripción",
          model: "description",
          placeholder: "Descripción del recurso",
          featured: true,
          required: true,
        },
        {
          type: "textArea",
          label: "Palabras clave",
          model: "key_words",
          hint: "Máximo 5 palabras",
          max: 200,
          placeholder: "Máximo 5 palabras separadas por ,",
          rows: 2,
        },
        {
          type: "label",
          label: "<h3>Ciclo de vida</h3>",
          model: "created",
          styleClasses: "blue lighten-4 text-md-center",
        },
        {
          type: "input",
          inputType: "number",
          label: "Versión",
          model: "version",
          min: 0,
          max: 200,
          placeholder: "Número de la versión del recurso",
          featured: true,
          required: true,
        },
        {
          type: "select",
          inputType: "text",
          label: "Estado",
          model: "state",
          placeholder: "Estado del del recurso",
          featured: true,
          required: true,
          values: ["Aprobado", "No aprobado"],
          default: "Por aprobar",
        },
        {
          type: "textArea",
          label: "Autores",
          model: "participants",
          hint: "Autores del recurso",
          max: 200,
          placeholder: "Nombres de los utores separados por coma",
          rows: 2,
        },
        {
          type: "label",
          label: "<h3>Características pedagógicas</h3>",
          model: "created",
          styleClasses: "blue lighten-4 text-md-center",
        },
        {
          type: "select",
          inputType: "text",
          label: "Tipo de aprendizaje",
          model: "class_learning",
          placeholder:
            "El tipo de aprendizaje predominante soportado por este recurso.",
          featured: true,
          required: true,
          values: ["Activo", "Expositivo", "Combinado"],
          default: "Activo",
        },
        {
          type: "input",
          inputType: "text",
          label: "Tipo de recurso educativo",
          model: "type_of_educational_resource",
          placeholder: "Tipo de recurso educativo",
          featured: true,
          required: true,
        },
        {
          type: "select",
          inputType: "text",
          label: "Nivel de interación",
          model: "level_of_interaction",
          placeholder:
            "El tipo de aprendizaje predominante soportado por este recurso.",
          featured: true,
          required: true,
          values: ["Muy bajo", "Bajo", "Medio Alto", "Muy alto"],
          default: "Muy bajo",
        },
        {
          type: "input",
          inputType: "text",
          label: "Población objetivo",
          model: "objetive_poblation",
          placeholder:
            "El usuario principal para el que ha sido diseñado este recurso.",
          featured: true,
          required: true,
        },
        {
          type: "input",
          inputType: "text",
          label: "Contexto",
          model: "context",
          placeholder: "El entorno principal en el que se utilizará.",
          featured: true,
          required: true,
        },
        {
          type: "label",
          label: "<h3>Derechos de uso</h3>",
          model: "created",
          styleClasses: "blue lighten-4 text-md-center",
        },
        {
          type: "select",
          inputType: "text",
          label: "Copyright",
          model: "copyright",
          placeholder: "Tipo de derechos",
          featured: true,
          required: true,
          values: [
            "Atribución",
            "Atribución-CompartirIgual",
            "Atribución-SinDerivadas",
            "Atribución-NoComercial",
            "Atribución-NoComercial-CompartirIgual",
            "Atribución-NoComercial-SinDerivadas",
          ],
          default: "Atribución",
          help: `para mas información <a target="_blank" href="https://creativecommons.org/licenses/?lang=es">Creative Commons</a>`,
        },
        {
          type: "label",
          label: "<h3>Anotación</h3>",
          model: "created",
          styleClasses: "blue lighten-4 text-md-center",
        },
        {
          type: "input",
          inputType: "text",
          label: "Entidad",
          model: "entity",
          placeholder: "Entidad",
          value: "Universidad Distrital Francisco José de Caldas",
          disabled: true,
          featured: true,
          required: true,
        },
        {
          type: "input",
          inputType: "date",
          label: "Fecha",
          model: "date",
        },
        {
          type: "checklist",
          label: "Clasificación",
          model: "purpose",
          listBox: true,
          values: [
            "Agronomía, Veterinaria y afines",
            "Bellas Artes",
            "Ciencias de la Educación",
            "Ciencias de la Salud",
            "Ciencias Sociales y Humanas",
            "Economía, Administración, Contaduría y afines",
            "Ingeniería, Arquitectura, Urbanismo y afines",
            "Matemáticas y Ciencia Naturales",
          ],
          help: `para mas información <a target="_blank" href="https://creativecommons.org/licenses/?lang=es">Areas del conocimiento</a>`,
        },
        {
          type: "input",
          inputType: "text",
          label: "Correo electronico",
          model: "email",
          placeholder: "Correo electronico",
          featured: true,
          required: true,
        },
        {
          type: "submit",
          buttonText: "Crear Recurso",
          onSubmit: (model) => this.submit(model),
        },
      ],
    },
    formOptions: {
      validateAfterLoad: false,
      validateAfterChanged: true,
      validateAsync: true,
    },
  }
export default {
addFiles
}